version: '3'

services:
  redis-server:
    image: 'redis'
    networks:
      - redis_node
  node-app:
    build: .
    restart: on-failure
    ports: 
      - "8080:8080"
    networks:
      - redis_node

networks:
  redis_node:
    driver: 'bridge'